name: Build and Deploy Astro Site

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Astro site
        run: npm run build

      - name: Upload dist folder as artifact
        uses: actions/upload-artifact@v3
        with:
          name: astro-dist
          path: dist/
